Document: elboukhari
Title: Debian elboukhari Manual
Author: <insert document author here>
Abstract: This manual describes what elboukhari is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/elboukhari/elboukhari.sgml.gz

Format: postscript
Files: /usr/share/doc/elboukhari/elboukhari.ps.gz

Format: text
Files: /usr/share/doc/elboukhari/elboukhari.text.gz

Format: HTML
Index: /usr/share/doc/elboukhari/html/index.html
Files: /usr/share/doc/elboukhari/html/*.html
